version: "3"

services:
  auth-db:
    image: postgres:latest
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - CommunicationWithMicroservices
    ports:
      - 5432:5432
  product-db:
    image: postgres:latest
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - CommunicationWithMicroservices
    ports:
      - 5433:5432
  sales-db:
    image: mongo:latest
    container_name: sales-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    networks:
      - CommunicationWithMicroservices
    ports:
      - 27017:27017
      - 28017:28017
  auth-api:
    build: './auth-api'
    container_name: auth-api
    environment:
      - PORT=8080
    networks:
      - CommunicationWithMicroservices
    ports:
      - 8080:8080
  product-api:
    build: './product-api'
    container_name: product-api
    environment:
      - PORT=8081
    networks:
      - CommunicationWithMicroservices
    ports:
      - 8081:8081
  sales-api:
    build: './sales-api'
    container_name: sales-api
    environment:
      - PORT=8082
    networks:
      - CommunicationWithMicroservices
    ports:
      - 8082:8082
  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    networks:
      - CommunicationWithMicroservices
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
networks:
  CommunicationWithMicroservices:
    driver: bridge